-- Secure Question Paper Portal
-- Run this whole file in Supabase SQL Editor.

create extension if not exists pgcrypto;

create type public.user_role as enum (
  'admin',
  'question_setter',
  'exam_officer',
  'exam_centre'
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default 'User',
  role public.user_role not null default 'question_setter',
  created_at timestamptz not null default now()
);

create table if not exists public.papers (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  subject text not null,
  encrypted_content text not null,
  iv text not null,
  auth_tag text not null,
  watermark_id text not null unique,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  paper_id uuid references public.papers(id) on delete set null,
  action text not null,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.audit_logs
  add column if not exists copy_watermark_id text;

alter table public.profiles enable row level security;
alter table public.papers enable row level security;
alter table public.audit_logs enable row level security;

create or replace function public.current_user_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid()
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', 'User')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Profiles: a user can read their own profile; admins can read all.
drop policy if exists "profiles self read" on public.profiles;
create policy "profiles self read"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.current_user_role() = 'admin');

-- Paper rows are accessed only through server routes. Browser clients must not
-- be able to retrieve ciphertext and attempt to bypass application controls.
drop policy if exists "papers authorized read" on public.papers;
create policy "papers authorized read"
on public.papers for select
to authenticated
using (false);

drop policy if exists "papers setters insert" on public.papers;
create policy "papers setters insert"
on public.papers for insert
to authenticated
with check (
  false
);

-- Audit logs: users may insert their own audit record; admins/officers can read.
drop policy if exists "audit insert own" on public.audit_logs;
create policy "audit insert own"
on public.audit_logs for insert
to authenticated
with check (false);

drop policy if exists "audit authorized read" on public.audit_logs;
create policy "audit authorized read"
on public.audit_logs for select
to authenticated
using (
  public.current_user_role() in ('admin','exam_officer')
);

-- Helpful indexes.
create index if not exists papers_created_by_idx on public.papers(created_by);
create index if not exists papers_created_at_idx on public.papers(created_at desc);
create index if not exists audit_created_at_idx on public.audit_logs(created_at desc);
create index if not exists audit_paper_idx on public.audit_logs(paper_id);

-- IMPORTANT:
-- For an academic demo, the service-role server client is used only inside API routes
-- after checking the authenticated user's role. Never expose that key to the browser.
